### PR TITLE
Allow for configuration of both go-sbot and sbotcli

### PR DESCRIPTION
**Pull request by KyleMaas**
See #151 

Not quite done yet, but making progress.

### CODE REVIEW

**Comment by KyleMaas** [comment]
@decentral1se I think this is pretty well ready to go.  I haven't done much testing other than the automated test suite, though, so if you could look this over carefully please that'd be great.

Only thing I don't like about it is that it doesn't autodetect the previous style of configuration file and just deal with it - instead it complains until you update the format of your existing files.  I mean, the project's still technically in "alpha", but I don't like the breaking change aspect of it.  However I'm not really sure how to do that elegantly with the way the config file is currently being parsed.

**Review by decentral1se — COMMENTED** [review]
@KyleMaas Great work! Nothing jumps out at me after a pass on the code. Testing it locally, I can see stuff getting picked up nicely.

As I understand it `no [go-sbot] detected in config file` means "I am not reading anything from the config file"? Maybe we could update that warning to be more explicit?

I noticed that now that `presence` :point_right: `Presence`, it's getting persisted in the `running-config.json` but wasn't before? I don't think we want that to get persisted or?

```
cat .ssb-go/running-config.json
{
  "repo": "/home/d",
  "nounixsock": false,
  "localadv": false,
  "localdiscov": false,
  "enable-ebt": false,
  "promisc": false,
  "repair": false,
  "Presence": {}
}
```

**Comment by KyleMaas** [comment]
@decentral1se Thanks for taking a look!

Re: warning - yes, that means no configuration is being picked up.  I can change that.

Re: Presence - yes, since it's its own module now, `presence` needed to be changed to `Presence` so that it could be accessed from outside of the module.  I can try and figure out where that's persisted from and take that out of the export.

**Comment by KyleMaas** [comment]
@decentral1se How's that look?

**Review by decentral1se — APPROVED** [review]
LGTM! Thanks!

**Comment by KyleMaas** [comment]
Awesome.  Thanks!

**Pull request merged**
