### PR TITLE
Migrate to ssbc urls

### PR DESCRIPTION
**Pull request by decentral1se**
Closes https://github.com/ssbc/go-ssb/issues/160.

~~Awaits the migration of https://git.sr.ht/~cryptix/go-gabbygrove, have pinged @cryptix on ssb.~~

### CODE REVIEW

**Comment by decentral1se** [comment]
@staltz (sorry for so many pings :fearful: ) perhaps you could also migrate it? I could also but missing ssbc org perms.

**Comment by staltz** [comment]
@decentral1se Does it work if you create the repo on GitHub and then transfer it to ssbc?

**Comment by staltz** [comment]
@decentral1se Oh, sorry, I thought it worked differently. In any case, there is now https://github.com/ssbc/go-gabbygrove

Hopefully soon enough you'll be admitted to SSBC via [membership rules](https://github.com/ssbc/.github/blob/master/MEMBERSHIP.md).

**Review by staltz — APPROVED** [review]
You know what, I'm not going to look at all the 261 files changed, I'm going to trust CI tests and trust you. :)

**Pull request merged**
