### PR TITLE
replace file reading with file execution!

### PR DESCRIPTION
**Pull request by mixmix**
this is a cosmetic PR really. I think you can trim these lines. You might need then to make those files executable and put a `#! /usr/bin/env node` at the top of the files

### CODE REVIEW

**Comment by cryptix** [comment]
Thanks for dipping your toes in! :) Initially I did pass strings to eval directly from env but it felt way to weird. Looking at it again zoomed out more,  I guess it could even be a module and export `before` and `after` functions.

**Comment by cryptix** [comment]
Finally got around to trying this, on [go-ssb-room](https://git.sr.ht/~cryptix/go-ssb-rooms/commit/1269b30f151a295c35ad3e6467cef45eacd3cdbf) though, where I took the chance to start with a cleaner slate.

I chose to require the scripts (expecting a from of two exported functions) and pass the helpers that were in scope of the eval. The error messages alone make this worth while, not being clouded in _somewhere in the eval_. Just not sure when I get around to porting the test corpus here but it _should_ definitely happen.

**Comment by decentral1se** [comment]
Not sure on the state of this folks, should it be merged or adapted? @mixmix @cryptix

**Comment by decentral1se** [comment]
Unsure of status (https://github.com/ssbc/go-ssb/pull/20#issuecomment-1192563174), unsure folks are coming back to this one. Will close off for now.

**Pull request closed without merging**
