### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by locriacyber**

### CODE REVIEW

**Review by decentral1se — APPROVED** [review]
:100:

**Comment by staltz** [comment]
I'm wondering what's up with the CI tests.

**Comment by decentral1se** [comment]
Perhaps flaking tests, can we re-run the CI? Might warrant further investigation if it fails again...

**Comment by mplorentz** [comment]
I have no idea why CI is failing, but it’s been that way for like a year https://github.com/ssbc/go-ssb/pulls?q=is%3Apr+is%3Aclosed

**Pull request merged**
