### PR TITLE
feat: badger lite & limited replication backports

### PR DESCRIPTION
**Pull request by decentral1se**
For https://github.com/ssbc/go-ssb/issues/124 testing @mycognosist @interfect @luandro @vielmetti @ahdinosaur  :construction: 

Now that https://github.com/ssbc/go-ssb/pull/176 landed, the new BadgerDB data store is incompatible with previous versions afaiu. So, please back up your `~/.ssb-go` before testing if you still have one! Best start from a fresh `~/.ssb-go` / keypair while testing, I guess. There may be some way to migrate it forward, can take a look if you need that.

There could be more to tweak in the new BadgerDB configuration, we can consult https://github.com/dgraph-io/badger/blob/main/docs/content/get-started/index.md#memory-usage & https://pkg.go.dev/github.com/dgraph-io/badger/v3#Options.

This PR adds a new lightweight BadgerDB config that @mplorentz / @boreq @ Planetary have been running and backports (slightly re-worked) several commits that @boreq implemented which allow us to limit the amount of concurrent replication that is allowed. This means we should be able to limit `go-sbot` from OOM'ing.

There are still some bugs with replication but let's put those aside for the moment... we just want the thing to run for the moment :sweat_smile: 

You can test this with the following commands:

```
git clone https://github.com/decentral1se/ssb
cd ssb
git checkout lite-fixes
go build -tags lite -v ./cmd/go-sbot
go build -v ./cmd/sbotcli
```

You'll notice two new flags on `go-sbot` (should also be available in the config):

```
  -numPeer uint
    	how many feeds can be replicated with one peer connection (shouldn't be higher than numRepl) (default 5)
  -numRepl uint
    	how many feeds can be replicated concurrently (default 10)
```

I followed the defaults of Planetary who are targetting iOS, you may need to tweak it!

Good luck and do let me know :woman_dancing:

### CODE REVIEW

**Comment by decentral1se** [comment]
OK the [CI failure](https://github.com/ssbc/go-ssb/actions/runs/3341604587) does seem to be relevant, also able to reproduce some of the errors but local `go-ssb` / Patchwork replication testing is work :thinking: Looks like I will need to fix that. The main part of the error appears to be:


> level=debug t=1m56.723971106s peer=<@FnnU.ed25519> conn="serve exited" err="muxrpc: error unpacking request: new request -1986621301: error decoding packet: invalid character 's' looking for beginning of value"

**Comment by mycognosist** [comment]
Thanks for this, @decentral1se ! I've begun testing.

I know you mention that there are still some bugs in replication but I have one question: do the `numPeer` and `numRepl` settings take effect regardless of whether replication is legacy or EBT? Or are those parameters only relevant for defining legacy replication configuration?

**Comment by decentral1se** [comment]
> Thanks for this, @decentral1se ! I've begun testing.

Woohoo @mycognosist :fireworks: 

> I know you mention that there are still some bugs in replication but I have one question: do the numPeer and numRepl settings take effect regardless of whether replication is legacy or EBT? Or are those parameters only relevant for defining legacy replication configuration?

Ah, great question! Still learning the ropes here but I believe this is only supported in legacy gossip (code changes in `plugins/gossip` vs. `plugins/ebt`). Forgot to mention that! The next wave of backport fixes are all for replication (both legacy / ebt) so maybe I should get backportin' for better testing :upside_down_face: 

Did you have some success in testing? :nerd_face:

**Comment by decentral1se** [comment]
@mycognosist I've merged this #180 (this PR with latest changes) #179 & #178 into https://github.com/decentral1se/ssb/tree/fork-backports-exp alongside all the replication related backports I've adapted from https://github.com/planetary-social/ssb/tree/fork which are general & relevant. That might be a better testing base for replication... similar testing instructions apply:

```
git fetch -a  # assuming you're still in a clone of https://github.com/decentral1se/ssb
git checkout fork-backports-exp
go build -tags lite -v ./cmd/go-sbot
go build -v ./cmd/sbotcli
```

Once #180 #179 #178 get merged, I'll cut a new PR with the replication backports proper.

**Comment by mycognosist** [comment]
@decentral1se 

Thanks for the answer and for getting these backports merged for testing so quickly. You're on a roll!

I'm currently running a test of `fork-backports-exp` with EBT enabled. Then I think I might get my Orange Pi Zero out and see if I have any luck with that. I'm not intending to run go-sbot on that board under usual circumstances but it might be nice to have a test run on a very low-spec board, especially since others have tried on the Zero before.

**Comment by mycognosist** [comment]
@decentral1se 

I tried to build on my Orange Pi Zero but ran into an error with `go-muxrpc`: https://github.com/ssbc/go-muxrpc/issues/13

**Comment by decentral1se** [comment]
> I tried to build on my Orange Pi Zero but ran into an error with go-muxrpc: https://github.com/ssbc/go-muxrpc/issues/13

https://github.com/ssbc/go-muxrpc/issues/13#issuecomment-1295895056

**Comment by decentral1se** [comment]
@staltz think this is good to merge now also!

We're seeing success on rpi 4 / orange pi zero builds thanks to the testing efforts of @mycognosist :1st_place_medal: 

This should close https://github.com/ssbc/go-ssb/issues/86 https://github.com/ssbc/go-ssb/issues/124 https://github.com/ssbc/go-ssb/issues/95

**Review by staltz — APPROVED** [review]
:dove:

**Pull request merged**
